import React, { Component } from 'react';

class Post2 extends Component {
  render() {
    return (
      <div>
        <h1>My Coding Bootcamp Experience</h1>
        <p>
          I first started learning to code in November of 2017. I started learning by going through video tutorials on Teamtreehouse.com. This learning strategy continued for a few months. However, in April of 2018, I decided that going to a coding bootcamp would be beneficial for me. I felt like I was learning too slow on my own, and I kept running into bugs in my code that sometimes took days for me to figure out (I thought that with the help of an instructor I could learn how to solve these bugs way faster). So, I signed up for the three month Web Development Immersive Program through General Assembly, which began on May 21st of 2018. With about six months of HTML, CSS, and a basic understanding of JavaScript under my belt, I thought I would have a leg up in the class. Boy was I completely wrong. In all honesty, I was probably the least experienced in the class. We were taught and expected to understand all the previous knowledge of web development I had by the end of the first week. So basically,  everything else I learned after that was completely new to me. The first week of class was all about the front end fundamentals: HTML, CSS, and JavaScript. The first homework assignment that got the best of me was the JavaScript clock we had to do. Using Vanilla JavaScript, we had to make an hour, minute, and second hand turn around a clock face, giving the current time of day. I still remember me and four other of my classmates staying four hours after class with the Instructor Assistant, Kyle, trying to explain to us how to get our JavaScript clocks working. That was when I first began to realize what exactly I signed up for. I knew before I signed up, the bootcamp would be hard, but you never realize how hard exactly it will be until you're actually doing it. The Next big assignment was over the first weekend, where we had to make a tic-tac-toe application. It seemed simple enough, but with my lack of experience, it proved to be a major problem for me. I ended up figuring it out but ...

          Four main things I got out of attending General Assembly. One, I learned how to actually write code and test it line by line and being able to actually create projects. Two, I learned how to look things up on Google and try to solve problems and errors on my own. As obvious as it sounds to just Google a problem you have, it's really actually kind of skill. You have to understand what your question is and where to actually look. Two great resources are W3schools and Stackoverflow. These two sites help me out tremendously, especially with my debugging pursuits. Three, I gained a lot of knowledge from my classmates. I was lucky enough to have a lot of very skilled developers in my class and some of them took on the role of student-teacher to show me how to work through coding problems. Four, I had two amazing instructors. I'm pretty sure one of the biggest factors of your experience at a coding bootcamp is whethor or not you have good instructors. The head instructor that I had, had 15+ years of experience. Along with that he was also very clear in his instruction. It's hard enough to learn to code as it is, and when you get clear instruction, it helps so much. I also had a really good Assistant instructor. This guy was really good at debugging code and he was kind of a JavaScript master.

          Here is some advice for anyone that has decided to go to a coding bootcamp. One, take a full stack JavaScript course online, before you go to a coding bootcamp. I didn't do that, but by week three of General Assembly, I wish I had. The more you know about the back end, creating routes, and understanding how to set up databases, the better experience you will have at one of these bootcamps. I would not recommend for anyone with no experience to jump right into a coding bootcamp. Two, sit at the front of the class. Some of these lectures can be long and it's easy to space out. But, if you're sitting at the front you will have the lesson right in front of you and you will probably be more likely to focus and participate in class. This might not apply to everyone, but it worked for me. Three, make friends with everyone in the class. The instructor won't always be able to help you, so getting help from your classmates is perfect. There were about four people in my class that took on the role of student-teacher to help me understand lessons and help me when I was building my projects. 
        </p>
      </div>
    )
  }
}

export default Post2;
